---
ID: "d3919c33-63a0-458e-8c64-fa351b2103de"
Parent: "eb402b39-57b6-4abc-b488-06bb63fac1c6"
Template: "eb402b39-57b6-4abc-b488-06bb63fac1c6"
Path: /sitecore/templates/Project/Sites/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {EB402B39-57B6-4ABC-B488-06BB63FAC1C6}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241004T021728Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\shinichi.haramizu@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\shinichi.haramizu@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "44e8a65e-e8f8-4a5c-b5b8-ded309bfdd3c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shinichi.haramizu@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241004T021731Z
    - ID: "e8921a41-d3eb-4c15-a43f-f4d277e48b53"
      Hint: Title
      Value: $name
