---
ID: "ae852875-9b79-42a3-8625-8cdb93a31f4c"
Parent: "251ed9b4-6ff9-4828-8be4-1d5b8f5d356d"
Template: "251ed9b4-6ff9-4828-8be4-1d5b8f5d356d"
Path: /sitecore/templates/Project/Sites/Partial Design Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {251ED9B4-6FF9-4828-8BE4-1D5B8F5D356D}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240928T020035Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\shinichi.haramizu@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\shinichi.haramizu@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "835afb04-e198-4117-b2b6-a46a2fa67eda"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shinichi.haramizu@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240928T020036Z
